_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "/home/joseph/workspace/OWOD/output/t3_ft/model_final.pth"
  ROI_HEADS:
    NMS_THRESH_TEST: 0.4
TEST:
  DETECTIONS_PER_IMAGE: 100
DATASETS:
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (52000, 56000)
  MAX_ITER: 58000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t3_evalulate"
OWOD:
  PREV_INTRODUCED_CLS: 10
  CUR_INTRODUCED_CLS: 5