_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "/home/fk1/workspace/OWOD/output/t4/model_final.pth"
DATASETS:
  TRAIN: ('t4_voc_coco_2007_train', )
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (74000, 78000)
  MAX_ITER: 80000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t4"
OWOD:
  PREV_INTRODUCED_CLS: 15
  CUR_INTRODUCED_CLS: 5
  CLUSTERING:
    START_ITER: 62000