_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "/home/joseph/workspace/OWOD/output/t2_ft/model_final.pth"
TEST:
  DETECTIONS_PER_IMAGE: 50
DATASETS:
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (30000, 34000)
  MAX_ITER: 36000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t2_evaluate"
OWOD:
  PREV_INTRODUCED_CLS: 5
  CUR_INTRODUCED_CLS: 5
